name: wine-platform
adopt-info: wine
summary: wine platform snap it provides WINE for snaps
description: |
 This snap creates a WINE base via content sharing to be used by other snaps that are using WINE.

grade: stable
confinement: strict
platforms:
  amd64:
    build-on: amd64
    build-for: amd64
base: core24
compression: lzo

slots:
  wine-base-stable:
    interface: content
    source:
      read:
      - $SNAP/opt/wine-stable

  wine-base-devel:
    interface: content
    source:
      read:
      - $SNAP/opt/wine-devel

  wine-base-staging:
    interface: content
    source:
      read:
      - $SNAP/opt/wine-staging

parts:
  wine:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      craftctl default

      ARCH="$(dpkg --print-architecture)"
      WINE_VER="$(wget -qO- https://github.com/mmtrt/Wine-Builds/releases/expanded_assets/stable | grep -Eo '/wine-[0-9].*xz"' | cut -d'-' -f2 | head -1)"
      WINE_VER_DEV="$(wget -qO- https://github.com/mmtrt/Wine-Builds/releases/expanded_assets/latest | grep -Eo '[0-9].*xz"' | sed -r 's|-amd64| |' | head -1 | awk '{print $1}')"

      # set snap version
      craftctl set version="$WINE_VER-$WINE_VER_DEV"

      # wget and dpkg extract the wine debs
      (mkdir -p ${SNAPCRAFT_PART_INSTALL}/opt ; cd ${SNAPCRAFT_PART_INSTALL}/opt ; wget -q "https://github.com/mmtrt/Wine-Builds/releases/download/stable/wine-${WINE_VER}-amd64.tar.xz" ; tar -xf *.tar.xz ; rm *.tar.xz ; mv wine-11* wine-stable)
      (mkdir -p ${SNAPCRAFT_PART_INSTALL}/opt ; cd ${SNAPCRAFT_PART_INSTALL}/opt ; wget -q "https://github.com/mmtrt/Wine-Builds/releases/download/latest/wine-${WINE_VER_DEV}-amd64.tar.xz" ; tar -xf *.tar.xz ; rm *.tar.xz ; mv wine-11* wine-devel)
      (mkdir -p ${SNAPCRAFT_PART_INSTALL}/opt ; cd ${SNAPCRAFT_PART_INSTALL}/opt ; wget -q "https://github.com/mmtrt/Wine-Builds/releases/download/latest/wine-${WINE_VER_DEV}-staging-amd64.tar.xz" ; tar -xf *.tar.xz ; rm *.tar.xz ; mv wine-*-staging-amd64 wine-staging)

      # Cleanup
      for REL in wine-stable wine-devel wine-staging; do
      rm -rf ${SNAPCRAFT_PART_INSTALL}/opt/${REL}/share/applications
      rm -rf ${SNAPCRAFT_PART_INSTALL}/opt/${REL}/share/man
      # Disable winemenubuilder
      sed -i 's/winemenubuilder.exe -a -r/winemenubuilder.exe -r/g' "${CRAFT_PART_INSTALL}"/opt/${REL}/share/wine/wine.inf
      done
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/share/doc
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/share/lintian
